name: buildMultiPlatform
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: mv_file
        run: mv ./server/* .

      - name: install
        run: pip install -r requirements.txt & pip install pyinstaller

      - name: build
        run: pyinstaller __main__.py -F -p ./ --name exviewer -i build/favicon.ico --add-data "build:build"



      - name: Setup Debug Session
        uses: csexton/debugger-action@master

  # # build:
  # #   runs-on: ubuntu-latest
  # #   strategy:
  # #     fail-fast: false
  # #     matrix:
  # #       platform:
  # #         - linux/amd64
  # #         - linux/arm/v7
  # #         - linux/arm/v8
  # #         - linux/arm64
  # #   steps:
  # #     - uses: actions/checkout@v3

  # #     - uses: actions/setup-python@v4
  # #       with:
  # #         python-version: '3.9' 

  # #     

  # #     - name: build
  # #       run: |
  # #           cd server
  # #           pyinstaller __main__.py -F -p ./ --name exviewer-linux-amd64 -i ../build/favicon.ico --add-data "../build:build"

  # #     - name: Create GitHub release
  # #       uses: marvinpinto/action-automatic-releases@latest
  # #       with:
  # #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  # #         automatic_release_tag: ${{ github.event.client_payload.tag}}
  # #         title: ${{ github.event.client_payload.title}}
  # #         prerelease: false
  # #         files: ./server/dist/exviewer-linux-amd64


  # pyinstaller __main__.py -F -p ./ --name exviewer-linux-amd64 -i build/favicon.ico --add-data "build:build"