name: DeployUI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn install
      
      - name: build
        continue-on-error: true
        run: yarn build

      - name: mvBuild
        run: mv build release

      - name: move fake api
        run: mv src/components/api/fakeApi.js src/components/api/serverApi.js

      - name: build
        continue-on-error: true
        run: yarn build
        
      - name: mvBuild
        run: mv build release/demo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release

